#ifndef CONSTANTES_H
#define CONSTANTES_H

#define SEPARADOR_COLUNAS_ARQUIVO ' '
#define SEPARADOR_COMANDO ':'
#define ALL -1
#define INQUIRED_CARACTER '?'
#define AGGREGATED_CARACTER '*'

#define DIMENSAO_AGREGADA 1
#define DIMENSAO_INQUIRED 2
#define DIMENSAO_INSTANCIADA 3

#define MAX_KERNELS_SIMULTANEOS 40

#define INVALID_NUMBER -1
#define MAX_TAM_BUFFER 32000000
#define MAX_BARRAMENTO 30 * 1000 * 1000
#define PER_CENT_MEM 0.8
#define DEFAULT_BLOCK_SIZE 1024
#define DEFAULT_BLOCKS_PER_MULTIPROCESSOR 4096
#define DEBUG_GPU_H 0

#define TAMANHO_VARIAVEL 0
#define TAMANHO_FIXO 1

#define LABEL_INSTANCIADAS "INST"

#define SUCESSO_COPIA 0
#define ERRO_BUFFER 1
#define ERRO_GPU 2

#endif